site_name: My MkDocs Material Documentation
site_url: https://tleonhardt.github.io/mkdocs-material-tutorial
repo_url: https://github.com/tleonhardt/mkdocs-material-tutorial
repo_name: mkdocs-material-tutorial
edit_uri: edit/main/docs
docs_dir: docs
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    logo: material/book-open-variant
    edit: material/pencil
    view: material/eye
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    # - navigation.path
    - toc.follow
    - toc.integrate
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/github
      link: https://github.com/tleonhardt
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/todd-leonhardt-1976452/

copyright: Copyright &copy; 2024 Todd Leonhardt