site_name: My MkDocs Material Documentation
site_url: https://tleonhardt.github.io/mkdocs-material-tutorial

theme:
  name: material
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.footer
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: deep orange

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: light blue
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/github
      link: https://github.com/tleonhardt
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/todd-leonhardt-1976452/

copyright: Copyright &copy; 2024 Todd Leonhardt